const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:2000,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Puma Slim Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:4500,
            brand:'Puma',
            rating: 4.0,
            numReviews: 50,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Polo Slim Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:1000,
            brand:'Polo',
            rating: 5.0,
            numReviews: 90,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Denim Slim Shirt',
            category:'Shirts',
            image:'/images/p4.jpg',
            price:200,
            brand:'Denim',
            rating: 4.7,
            numReviews: 40,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Adidas Slim Shirt',
            category:'Shirts',
            image:'/images/p5.jpg',
            price:2500,
            brand:'Adidas',
            rating: 4.9,
            numReviews: 650,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Duke Slim Shirt',
            category:'Shirts',
            image:'/images/p6.webp',
            price:1500,
            brand:'Duke',
            rating: 4.7,
            numReviews: 154,
            description:'high quality product',
        },
    ],
};
export default data;